sudo: required
services:
    - docker
    
before_install:
    - docker build -t griffinsibm/docker-react -f Dockerfile.dev .

script:
    - docker run griffinsibm/docker-react npm run test -- --coverage
    